# Todo: Move logic from _exceptions.py to validate_exceptions. Have _exceptions call this.